require('dotenv').config();

module.exports = {
    SPEECH_API_SUBSCRIPTION_KEY: process.env.SPEECH_API_SUBSCRIPTION_KEY,
    SPEECH_API_SERVICE_REGION: process.env.SPEECH_API_SERVICE_REGION,
    AZURE_STORAGE_CONNECTION_STRING: process.env.AZURE_STORAGE_CONNECTION_STRING,
    TRANSLATOR_DOCUMENT_KEY: process.env.TRANSLATOR_KEY,
    TRANSLATOR_DOCUMENT_ENDPOINT: process.env.TRANSLATOR_DOCUMENT_ENDPOINT,
    TRANSLATOR_TEXT_ENDPOINT: process.env.TRANSLATOR_TEXT_ENDPOINT,
    LANGUAGE_KEY:process.env.LANGUAGE_KEY,
    LANGUAGE_ENDPOINT:process.env.LANGUAGE_ENDPOINT
}